export const projects = [
  {
    title: "6CardsGolf",
    githubLink: "https://github.com/VimeanSam/sixcardsgolf",
    description:
      "A full-stack, real-time web version of the classic card game. Built with a responsive React frontend and custom-designed Photoshop themes, the application runs on a Node.js backend using Socket.io for live turn management. Fully containerized and deployed on AWS with an NGINX reverse proxy, it leverages MongoDB for seamless player data storage.",
    pics: [
      "golf_1",
      "golf_2",
      "golf_3",
      "golf_4",
      "golf_5",
      "golf_6",
      "golf_7",
    ],
    mainpic: "golf_5",
    skills: "Node.js, Express, React.js, Socket.IO, MongoDB, AWS, NGINX",
    link: "",
  },
  {
    title: "GatorRenter",
    githubLink: "https://github.com/VimeanSam/GatorRenter",
    description:
      "A Zillow-inspired real estate rental web application built as a collaborative project for my Software Enginnering course at SFSU. Serving as the front-end developer, I designed and implemented the site identity, interactive district view, messaging templates, and responsive user forms. The entire user experience was crafted from scratch using Bootstrap, HTML, and CSS to ensure a polished, modern interface.",
    pics: [
      "GatorRenter_1",
      "GatorRenter_2",
      "GatorRenter_3",
      "GatorRenter_3b",
      "GatorRenter_4",
      "GatorRenter_5",
      "GatorRenter_6",
      "GatorRenter_7",
      "GatorRenter_8",
      "GatorRenter_9",
      "GatorRenter_11",
      "GatorRenter_12",
      "GatorRenter_13",
    ],
    mainpic: "GatorRenter_2",
    skills: "HTML, CSS, Bootstrap, Node.js, Express, MySQL",
    link: "",
  },
  {
    title: "Cinemarker",
    githubLink: "https://github.com/VimeanSam/CineMarker",
    description:
      "A dynamic movie discovery platform that enables users to search, browse detailed information, and bookmark their favorite films. Built with Next.js for high-performance client rendering, the application integrates a robust RapidAPI movie database to fetch real-time data and is seamlessly deployed on the Vercel platform.",
    pics: ["cine_1", "cine_2", "cine_3", "cine_4", "cine_5"],
    mainpic: "cine_1",
    skills: "React.js, Next.js, Vercel",
    link: "",
  },
  {
    title: "2D Tank Game",
    githubLink: "https://github.com/VimeanSam/Tank-Game",
    description:
      "A fast-paced, two-player local arcade game developed as a Software Development term project at SFSU. Built entirely in Java, the game features competitive arena mechanics including destructible environments, power-up systems like health restoration, and dynamic life tracking. It showcases core object-oriented programming principles through custom collision detection and real-time game loops.",
    pics: ["tank_1", "tank_2", "tank_3", "tank_4", "tank_5"],
    mainpic: "tank_1",
    skills: "Java",
    link: "",
  },
  {
    title: "REST API",
    githubLink: "https://github.com/VimeanSam/GatorRenter-District-API-Golang",
    description:
      "A custom REST API developed to enhance geographical data querying for the GatorRenter term project. Built from scratch during my spare time, the service exposes endpoints to retrieve popular San Francisco housing districts, filter locations by city regions, and calculate campus proximity using an dynamic 'less-than-or-equal-to' (lte) distance query.",
    pics: ["api_1", "api_2", "api_3"],
    mainpic: "api_3",
    skills: "Go",
    link: "",
  },
  {
    title: "Calculator GUI",
    githubLink: "https://github.com/VimeanSam/CalculatorGUI",
    pics: ["calc_1", "calc_2", "calc_3", "calc_4", "calc_5", "calc_6"],
    description:
      "A Java-based graphical calculator that accurately parses and evaluates complex infix expressions using standard mathematical order of operations (PEMDAS). Developed for a Software Development course, the application leverages custom data structures such as Stacks to convert infix notation to postfix, seamlessly connecting algorithmic logic with a responsive user interface.",
    mainpic: "calc_1",
    skills: "Java",
    link: "",
  },
  {
    title: "Interpreter",
    githubLink: "https://github.com/VimeanSam/The-Interpreter",
    description:
      "A Java-based mock interpreter built to parse, compile, and execute programs written in a proprietary language, 'X'. Developed for a Software Development course, the application simulates a virtual machine by processing compiled .x.cod bytecode files, demonstrating a deep understanding of lexical analysis, language runtimes, and low-level execution environments.",
    pics: [
      "interpreter_1",
      "interpreter_2",
      "interpreter_3",
      "interpreter_4",
      "interpreter_5",
    ],
    mainpic: "interpreter_1",
    skills: "Java",
    link: "",
  },
  {
    title: "Mock Linux Shell",
    githubLink: "https://github.com/VimeanSam/Shell",
    description:
      "A lightweight Linux command-line interpreter developed from scratch in C for an operating systems course. The shell replicates native terminal functionality by processing standard commands (like ls and cd), managing low-level process lifecycles via process forking, handling input/output redirection through piping, and leveraging Unix system calls like execvp().",
    pics: ["shell_1", "shell_2", "shell_3"],
    mainpic: "shell_2",
    skills: "C, Linux",
    link: "",
  },
];
